__author__ = "Julián Arenas-Guerrero"
__credits__ = ["Julián Arenas-Guerrero"]

__license__ = "Apache-2.0"
__maintainer__ = "Julián Arenas-Guerrero"
__email__ = "julian.arenas.guerrero@upm.es"


import duckdb
from typing import Iterable, List, Tuple, Set
from rdflib.store import Store
from rdflib.util import from_n3
from .types import Triple
from ..args_parser import load_config_from_argument
from ..mapping.mapping_parser import retrieve_mappings
import re
from rdflib import URIRef, Literal, BNode
from rdflib.term import Variable, Identifier
from rdflib.plugins.sparql.sparql import FrozenBindings, QueryContext
import rdflib.plugins.sparql.evaluate as sparql_evaluate
from rdflib.plugins.sparql.sparql import QueryContext
import rdflib.plugins.sparql as sp

_Triple = Tuple[Identifier, Identifier, Identifier]
BGP = List[_Triple]

from .types import BGP


# -----------------------------------------------------------------------------------------------------
# RML TEMPLATE AND RDF TERM MATCHING

def rml_template_to_regex(template: str) -> tuple[re.Pattern, list[str]]:
    """
    Convert an RML template string into a compiled regex
    and return the ordered list of reference names found in the template.

    Returns
    -------
    pattern : re.Pattern
        Regex with one named group per {reference}.
    references : list[str]
        Reference names in order of appearance.
    """
    parts = []
    references = []
    ref_count: dict[str, int] = {}
    i = 0

    while i < len(template):
        ch = template[i]

        if ch == '\\' and i + 1 < len(template):
            nxt = template[i + 1]
            if nxt in ('{', '}', '\\'):
                parts.append(re.escape(nxt))
                i += 2
                continue
            parts.append(re.escape('\\'))
            i += 1

        elif ch == '{':
            j = i + 1
            while j < len(template) and template[j] != '}':
                j += 1
            if j >= len(template):
                raise ValueError(f"Unclosed '{{' in RML template: {template!r}")

            ref_name = template[i + 1 : j]
            references.append(ref_name)

            # Regex group names must be valid Python identifiers
            safe = re.sub(r'\W', '_', ref_name)
            count = ref_count.get(safe, 0)
            ref_count[safe] = count + 1
            group_name = safe if count == 0 else f"{safe}_{count}"

            parts.append(f'(?P<{group_name}>.+?)')
            i = j + 1

        else:
            parts.append(re.escape(ch))
            i += 1

    return re.compile('^' + ''.join(parts) + '$'), references


def match_rml_template(rdf_term, template: str) -> dict[str, str] | None:
    """
    Match an RDF term against an RML template.

    Parameters
    ----------
    rdf_term : URIRef | Literal | BNode | str
        The RDF term to test.
    template : str
        The rr:template / rml:template string,
        e.g. "http://example.com/person/{ID}"

    Returns
    -------
    dict[str, str]
        Mapping {reference_name → matched_value} if the term matches.
    None
        If the term cannot have been generated by the template.
    """
    value = str(rdf_term)
    pattern, references = rml_template_to_regex(template)
    m = pattern.match(value)
    if m is None:
        return None

    groups = m.groupdict()
    ref_count: dict[str, int] = {}
    result: dict[str, str] = {}

    for ref_name in references:
        safe = re.sub(r'\W', '_', ref_name)
        count = ref_count.get(safe, 0)
        group_name = safe if count == 0 else f"{safe}_{count}"
        ref_count[safe] = count + 1

        if ref_name not in result:
            result[ref_name] = groups[group_name]
        else:
            result[f"{ref_name}#{count}"] = groups[group_name]

    return result


def match_triple_pattern(tp, rml_df):
    s_pat, p_pat, o_pat = tp

    # filter by term type
    if not isinstance(s_pat, Variable):
        if isinstance(s_pat, URIRef):
            rml_df = rml_df[rml_df["subject_termtype"] == 'http://w3id.org/rml/IRI']
        elif isinstance(s_pat, BNode):
            rml_df = rml_df[rml_df["subject_termtype"] == 'http://w3id.org/rml/BlankNode']

    if not isinstance(o_pat, Variable):
        if isinstance(o_pat, URIRef):
            rml_df = rml_df[rml_df["object_termtype"] == 'http://w3id.org/rml/IRI']
        elif isinstance(o_pat, Literal):
            rml_df = rml_df[rml_df["object_termtype"] == 'http://w3id.org/rml/Literal']
        elif isinstance(o_pat, BNode):
            rml_df = rml_df[rml_df["object_termtype"] == 'http://w3id.org/rml/BlankNode']


    # filter by term value
    rml_df.loc[:, "match"] = False
    for i, rule in rml_df.iterrows():
        s_match = p_match = o_match = False

        if isinstance(s_pat, Variable):
            s_match = True
        else:
            if str(rule['subject_map_type']) == 'http://w3id.org/rml/constant':
                if str(s_pat) == rule['subject_map_value']:
                    s_match = True
            elif str(rule['subject_map_type']) == 'http://w3id.org/rml/template':
                if match_rml_template(s_pat, str(rule['subject_map_value'])):
                    s_match = True

        if isinstance(p_pat, Variable):
            p_match = True
        else:
            if str(rule['predicate_map_type']) == 'http://w3id.org/rml/constant':
                if str(p_pat) == rule['predicate_map_value']:
                    p_match = True
            elif str(rule['predicate_map_type']) == 'http://w3id.org/rml/template':
                if match_rml_template(p_pat, str(rule['predicate_map_value'])):
                    p_match = True

        if isinstance(o_pat, Variable):
            o_match = True
        else:
            if str(rule['object_map_type']) == 'http://w3id.org/rml/constant':
                if str(o_pat) == rule['object_map_value']:
                    o_match = True
            elif str(rule['object_map_type']) == 'http://w3id.org/rml/template':
                if match_rml_template(o_pat, str(rule['object_map_value'])):
                    o_match = True

        if s_match and p_match and o_match:
            rml_df.at[i, "match"] = True

    rml_df = rml_df[rml_df['match']]

    return rml_df




# -----------------------------------------------------------------------------------------------------
# BGP JOIN ORDERING FUNCTION


# Well-known low-selectivity predicates — extend as needed for your dataset
LOW_SELECTIVITY_PREDICATES: frozenset[str] = frozenset({
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
    "http://www.w3.org/2000/01/rdf-schema#label",
    "http://www.w3.org/2000/01/rdf-schema#subClassOf",
    "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
    "http://www.w3.org/2000/01/rdf-schema#domain",
    "http://www.w3.org/2000/01/rdf-schema#range",
    "http://www.w3.org/2002/07/owl#sameAs",
    "http://www.w3.org/2004/02/skos/core#broader",
    "http://www.w3.org/2004/02/skos/core#narrower",
})


def _position_weight(pos: int) -> int:
    return {0: 1, 2: 2, 1: 3}[pos]


def _is_bound(term, ctx, bound_vars):
    if not isinstance(term, Variable):
        return True
    return term in bound_vars or ctx[term] is not None


def _triple_score(triple, ctx, bound_vars):
    """
    Four-level score tuple — lower is better, compared lexicographically:

    Level 0 – connectivity     : 0 if shares ≥1 bound var (or first triple),
                                 1 if fully disconnected (bind-join safety)
    Level 1 – predicate penalty: 1 if predicate is a known low-selectivity URI,
                                 0 otherwise
    Level 2 – unbound count   : number of unbound positions (0–3)
    Level 3 – positional weight: sum of weights for unbound positions
                                 subject=1, object=2, predicate=3
    """
    s, p, o = triple

    # Level 0: connectivity (critical for bind joins)
    connected = any(_is_bound(t, ctx, bound_vars) and isinstance(t, Variable)
                    for t in triple)
    # If bound_vars is empty this is the first triple — treat as connected
    l0 = 0 if (not bound_vars or connected) else 1

    # Level 1: predicate penalty
    l1 = 1 if (isinstance(p, URIRef) and str(p) in LOW_SELECTIVITY_PREDICATES) else 0

    # Levels 2 & 3: unbound count + positional weights
    l2 = l3 = 0
    for pos, term in enumerate(triple):
        if not _is_bound(term, ctx, bound_vars):
            l2 += 1
            l3 += _position_weight(pos)

    return (l0, l1, l2, l3)


def order_bgp(ctx, bgp):
    """
    Reorder BGP triple patterns for efficient bind-join left-deep evaluation.

    Scoring per triple (lower = execute earlier):
      1. Connectivity  — disconnected patterns are always deferred
      2. Predicate     — known low-selectivity predicates (rdf:type etc.) are penalised
      3. Unbound count — fewer free variables → smaller intermediate result
      4. Positional    — subject(1) > object(2) > predicate(3) for remaining ties

    After each pick the chosen triple's variables are added to bound_vars
    (join propagation), so connected follow-on patterns score better next round.
    """
    if len(bgp) <= 1:
        return list(bgp)

    bound_vars = {
        t for triple in bgp for t in triple
        if isinstance(t, Variable) and ctx[t] is not None
    }

    remaining = list(bgp)
    ordered = []

    while remaining:
        best = min(range(len(remaining)),
                   key=lambda i: _triple_score(remaining[i], ctx, bound_vars))
        chosen = remaining.pop(best)
        ordered.append(chosen)
        for t in chosen:
            if isinstance(t, Variable):
                bound_vars.add(t)

    return ordered





# -----------------------------------------------------------------------------------------------------
# RDFLIB QUERY EXECUTION

def custom_eval(ctx, part):
    if part.name == "BGP":
        ordered = order_bgp(ctx, part.triples)
        return sparql_evaluate.evalBGP(ctx, ordered)
    raise NotImplementedError



def virtualize_sparql(config, rml_df):
    rdflib_evalBGP = sparql_evaluate.evalBGP

    def __evalBGP__(ctx: QueryContext, bgp: BGP):
        # A SPARQL query executed over a non VIRTStore is evaluated as usual
        if not isinstance(ctx.graph.store, VIRTStore):
            return rdflib_evalBGP(ctx, bgp)
        if not bgp:
            yield ctx.solution()
            return

        for tp in bgp:
            rml_tp_df = match_triple_pattern(tp, rml_df)
            print(tp)

        # execute BGP

        # yield/return the results
        """
        for row in store.hdt_document.search_join(set(bgp)):
            # convert the ResultRow into a FrozenBindings object
            bindings = dict()
            for key in row.labels:
                bindings[Variable(key)] = row[key]
            yield FrozenBindings(ctx, bindings)
        return
        """
    # overrides RDFlib evalBGP function
    sparql_evaluate.evalBGP = __evalBGP__



class VIRTStore(Store):
    def __init__(self, config_path: str, configuration=None, identifier=None):
        super(VIRTStore, self).__init__(configuration=configuration, identifier=identifier)

        sp.CUSTOM_EVALS["order_bgp"] = custom_eval

        config = load_config_from_argument(config_path)

        rml_df, fnml_df, http_api_df = retrieve_mappings(config)
        config.set('CONFIGURATION', 'http_api_df', http_api_df.to_csv())
        # keep only asserted mapping rules
        rml_df = rml_df.loc[rml_df['triples_map_type'] == 'http://w3id.org/rml/TriplesMap']

        virtualize_sparql(config, rml_df)


    def triples(self, pattern, context) -> Iterable[Triple]:
        pass
        return

    def create(self, configuration):
        raise TypeError('The VIRT store is read only!')

    def destroy(self, configuration):
        raise TypeError('The VIRT store is read only!')

    def commit(self):
        raise TypeError('The VIRT store is read only!')

    def rollback(self):
        raise TypeError('The VIRT store is read only!')

    def add(self, _, context=None, quoted=False):
        raise TypeError('The VIRT store is read only!')

    def addN(self, quads):
        raise TypeError('The VIRT store is read only!')

    def remove(self, _, context):
        raise TypeError('The VIRT store is read only!')
